### PR TITLE
Update README link

### PR DESCRIPTION
**Pull request by leesongun**
This patch removes google translate from README link.

### CODE REVIEW

**Comment by nicolalandro** [comment]
Thank you for the readme update! Are you able to use the plugin? Did you use on Linux with flatpack? If you installed on different OS or without flatpack how to reach the gimp python to install requirements? (In this way it is possible to improve the install guide with also other information).

**Comment by leesongun** [comment]
I struggled to make it work on windows, but I ended up simply using linux+flatpak :) 
I think there's a bug that prevents installing python libraries on windows GIMP (weekly CI build), as `python -m pip install $(any library)` results in error. 
I found out similar thing happens even on linux if I use flatpak for weekly CI build. Maybe it's something wrong in CI build?

**Comment by nicolalandro** [comment]
Maybe It can be a pip problem? Did you try to upgrade It with `python -m pip install --upgrade pip`? How to reach the GIMP version of python on Windows ? (In order to add It on the guide, also with a beta flag, but something Is Better then nothing)

**Comment by leesongun** [comment]
I upgraded pip. I also tried:
1. Installing using `pip` bundled to system python and changing target directory : installation succeeded but `from PIL import Image` resulted in `cannot import name '_imaging' from 'PIL'`
2. Changing GIMP python interpreter to system python : I was unable to install PyGObject on windows, I am not familiar with MSYS2.
I used python interpreter by simply following the path : `(installation directory)\GIMP 2.99\bin\python.exe`

**Comment by nicolalandro** [comment]
Thank you for the pull request and for the feedback!

**Pull request merged**
